### ISSUE TITLE
ValueError: 'CWE-209' is not in list

### ISSUE THREAD

**Issue by Rishi8991** [das-lab/TAP#1]
Hi, I am getting the following error when I run TAP. 

```
Traceback (most recent call last):
  File "tap.py", line 302, in <module>
    train()
  File "tap.py", line 200, in train
    combined_x,combined_y = combine(safeFile,unsafeFile,unsafeYFile)
  File "tap.py", line 70, in combine
    y = np.concatenate((np.array([tran_label(i.strip()) for i in unsafe_labels]), np.array([tran_label("safe") for i in safe_tokens])))
  File "tap.py", line 70, in <listcomp>
    y = np.concatenate((np.array([tran_label(i.strip()) for i in unsafe_labels]), np.array([tran_label("safe") for i in safe_tokens])))
  File "tap.py", line 67, in tran_label
    y_oh[labels.index(label)] = 1
ValueError: 'CWE-209' is not in list
```

**Comment by Unothing** [comment]
I'm sorry for my mistakes.
In fact, I have deleted three subsets of less than 10 samples, which are
CWE-209: Information Exposure Through an Error Message, 
CWE-311: Missing Encryption of Sensitive Data 
CWE-327: Use of a Broken or Risky Cryptographic Algorithm.
